[package]
name = "blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"                                         #biblioteca timestamp
serde = { version = "1.0.106", features = ["derive"] } #serialização
serde_json = "1.0"                                     #serialização
sha2 = "0.10.0"                                        #biblioteca de cálculo de hash
